"""Django REST Framework + React + PostgreSQL stack template."""

STACK_TEMPLATE = {
    "name": "django_react_postgres",
    "display_name": "Django REST + React + PostgreSQL",
    "tech_stack": {
        "language": "python",
        "framework": "django",
        "database": "postgresql",
        "orm": "django-orm",
        "migration_tool": "django-migrations",
        "auth": "jwt",
        "css": "tailwind",
        "package_manager": "pip",
        "runtime": "gunicorn",
        "frontend_framework": "react",
        "frontend_language": "typescript",
        "frontend_package_manager": "npm",
    },
    "base_directory_structure": [
        "backend/",
        "backend/manage.py",
        "backend/config/",
        "backend/config/__init__.py",
        "backend/config/settings/",
        "backend/config/settings/__init__.py",
        "backend/config/settings/base.py",
        "backend/config/settings/development.py",
        "backend/config/settings/production.py",
        "backend/config/urls.py",
        "backend/config/wsgi.py",
        "backend/config/asgi.py",
        "backend/apps/",
        "backend/apps/__init__.py",
        "backend/apps/users/",
        "backend/apps/users/__init__.py",
        "backend/apps/users/models.py",
        "backend/apps/users/serializers.py",
        "backend/apps/users/views.py",
        "backend/apps/users/urls.py",
        "backend/apps/users/admin.py",
        "backend/apps/api/",
        "backend/apps/api/__init__.py",
        "backend/apps/api/views.py",
        "backend/apps/api/urls.py",
        "backend/apps/api/serializers.py",
        "backend/apps/api/permissions.py",
        "backend/requirements/",
        "backend/requirements/base.txt",
        "backend/requirements/development.txt",
        "backend/requirements/production.txt",
        "backend/tests/",
        "backend/tests/__init__.py",
        "frontend/",
        "frontend/src/",
        "frontend/src/index.tsx",
        "frontend/src/App.tsx",
        "frontend/src/components/",
        "frontend/src/pages/",
        "frontend/src/hooks/",
        "frontend/src/api/",
        "frontend/src/types/",
        "frontend/public/",
        "frontend/package.json",
        "frontend/tsconfig.json",
        "frontend/tailwind.config.js",
        "docker/",
        "docker/backend.Dockerfile",
        "docker/frontend.Dockerfile",
        "docker-compose.yml",
        "docker-compose.prod.yml",
        ".env.example",
        ".gitignore",
        "README.md",
        "Makefile",
    ],
    "base_dependencies": {
        "runtime": [
            "django>=4.2",
            "djangorestframework",
            "djangorestframework-simplejwt",
            "django-cors-headers",
            "psycopg2-binary",
            "python-decouple",
            "gunicorn",
            "whitenoise",
            "drf-spectacular",
        ],
        "dev": [
            "pytest",
            "pytest-django",
            "factory-boy",
            "coverage",
            "black",
            "ruff",
            "mypy",
            "django-stubs",
        ],
    },
    "docker_services": {
        "db": {
            "image": "postgres:16-alpine",
            "env": {"POSTGRES_DB": "${DB_NAME}", "POSTGRES_USER": "${DB_USER}", "POSTGRES_PASSWORD": "${DB_PASSWORD}"},
            "ports": ["5432:5432"],
            "volumes": ["postgres_data:/var/lib/postgresql/data"],
        },
        "backend": {
            "build": "./docker/backend.Dockerfile",
            "command": "gunicorn config.wsgi:application --bind 0.0.0.0:8000",
            "ports": ["8000:8000"],
            "depends_on": ["db"],
        },
        "frontend": {
            "build": "./docker/frontend.Dockerfile",
            "ports": ["3000:3000"],
        },
    },
    "env_vars": [
        "SECRET_KEY",
        "DEBUG",
        "DB_NAME",
        "DB_USER",
        "DB_PASSWORD",
        "DB_HOST",
        "DB_PORT",
        "ALLOWED_HOSTS",
        "CORS_ALLOWED_ORIGINS",
        "JWT_SECRET_KEY",
    ],
    "feature_flags": {
        "has_auth": True,
        "has_frontend": True,
        "has_docker": True,
        "has_tests": True,
        "has_migrations": True,
        "has_admin": True,
    },
}
