"""React + Vite + TypeScript + Tailwind stack template."""

STACK_TEMPLATE = {
    "name": "react_vite",
    "display_name": "React + Vite + TypeScript",
    "template_dir": None,
    "tech_stack": {
        "language": "typescript",
        "framework": "react",
        "bundler": "vite",
        "database": "none",
        "css": "tailwindcss",
        "package_manager": "npm",
        "runtime": "browser",
        "auth": "none",
        "testing": "vitest",
    },
    "base_directory_structure": [
        "src/",
        "src/components/",
        "src/components/ui/",
        "src/pages/",
        "src/hooks/",
        "src/lib/",
        "src/types/",
        "src/assets/",
        "src/main.tsx",
        "src/App.tsx",
        "src/index.css",
        "src/vite-env.d.ts",
        "public/",
        "tests/",
        "index.html",
        ".env.example",
        "vite.config.ts",
        "tailwind.config.ts",
        "postcss.config.cjs",
        "tsconfig.json",
        "tsconfig.node.json",
    ],
    "base_dependencies": {
        "runtime": [
            "react",
            "react-dom",
            "react-router-dom",
        ],
        "dev": [
            "vite",
            "@vitejs/plugin-react",
            "typescript",
            "@types/react",
            "@types/react-dom",
            "tailwindcss",
            "postcss",
            "autoprefixer",
            "vitest",
            "@testing-library/react",
            "@testing-library/jest-dom",
        ],
    },
    "run_commands": {
        "install": "npm install",
        "dev": "npm run dev",
        "build": "npm run build",
        "test": "npm run test",
        "lint": "npx tsc --noEmit",
    },
    "env_vars": [
        {
            "name": "VITE_API_URL",
            "description": "Backend API URL",
            "example_value": "http://localhost:8000",
            "required": False,
        },
    ],
    "docker_services": [],
    "blueprint_hints": {
        "api_style": "REST / SWR for data fetching",
        "state": "React useState/useContext or Zustand",
        "routing": "React Router v6",
        "forms": "react-hook-form",
        "styling": "Tailwind CSS utility classes",
    },
}
